# Generated by Django 5.2 on 2025-04-27 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
