# Generated by Django 5.2 on 2025-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                default="Expense",
                max_length=7,
            ),
        ),
    ]
