# Generated by Django 5.2 on 2025-04-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_category_is_default_category_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.category",
            ),
            preserve_default=False,
        ),
    ]
