# Generated by Django 5.2 on 2025-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=5),
        ),
    ]
